GET http://localhost:4000/tasks/

###
POST http://localhost:4000/pages
Content-Type: application/json

{
    "title": "Ecodrive"
}

###

GET http://localhost:4000/tasks/4

###

PUT http://localhost:4000/pages/4
Content-Type: application/json

{
  "title": "Twitter"
}

###

DELETE http://localhost:4000/pages/4