POST http://localhost:4000/users
Content-Type: application/json

{
    "firstname": "Jonathan",
    "lastname": "larquetoux",
    "email": "maximelarquetoux@gmail.com",
    "password": "password",
    "imageUrl": "azerty"
}

###

GET http://localhost:4000/users

###

GET http://localhost:4000/users/3

###

PUT http://localhost:4000/users/3
Content-Type: application/json

{
  "firstname": "maxime"
}

###

DELETE http://localhost:4000/users/2